export const houseData = [
    {
      id: 1,
      title: 'Modern Family Home',
      description: 'A beautiful and spacious 3-bedroom house perfect for a growing family.',
      price: '$350,000',
      location: 'Los Angeles, CA',
      bedrooms: 3,
      bathrooms: 2,
      image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house1', // External link
    },
    {
      id: 2,
      title: 'Luxury Villa',
      description: 'An elegant 5-bedroom villa with a private pool and garden, located in a peaceful neighborhood.',
      price: '$1,200,000',
      location: 'Miami, FL',
      bedrooms: 5,
      bathrooms: 4,
      image: 'https://images.unsplash.com/photo-1600607681229-0f6f59c6f5f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house2',
    },
    {
      id: 3,
      title: 'Cozy Cottage',
      description: 'A charming 2-bedroom cottage located in the countryside, perfect for a weekend getaway.',
      price: '$250,000',
      location: 'Nashville, TN',
      bedrooms: 2,
      bathrooms: 1,
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house3',
    },
    {
      id: 4,
      title: 'Downtown Apartment',
      description: 'A stylish 2-bedroom apartment located in the heart of the city with amazing skyline views.',
      price: '$450,000',
      location: 'New York, NY',
      bedrooms: 2,
      bathrooms: 2,
      image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house4',
    },
    {
      id: 5,
      title: 'Suburban Dream Home',
      description: 'Spacious 4-bedroom home in a quiet suburban neighborhood, ideal for families.',
      price: '$550,000',
      location: 'Austin, TX',
      bedrooms: 4,
      bathrooms: 3,
      image: 'https://images.unsplash.com/photo-1597098652974-4f0f11065ab5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house5',
    },
    {
      id: 6,
      title: 'Beachfront Property',
      description: 'A luxurious 3-bedroom home with direct beach access and breathtaking ocean views.',
      price: '$850,000',
      location: 'Malibu, CA',
      bedrooms: 3,
      bathrooms: 3,
      image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house6',
    },
    {
      id: 7,
      title: 'Mountain Cabin',
      description: 'A rustic 3-bedroom cabin located in the mountains, offering stunning views and tranquility.',
      price: '$300,000',
      location: 'Denver, CO',
      bedrooms: 3,
      bathrooms: 2,
      image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house7',
    },
    {
      id: 8,
      title: 'Penthouse Suite',
      description: 'An exclusive 4-bedroom penthouse with panoramic city views and a private rooftop terrace.',
      price: '$2,500,000',
      location: 'Chicago, IL',
      bedrooms: 4,
      bathrooms: 4,
      image: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNzU3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&q=80&w=1080',
      link: 'https://www.example.com/house8',
    },
  ];
  